---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pv-claim
  labels:
    app: schools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: schools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schools
      tier: postgres
  template:
    metadata:
      labels:
        app: schools
        tier: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-pass
                  key: password
            - name: POSTGRES_USER
              value: application
            - name: POSTGRES_DB
              value: schools
          volumeMounts:
            - name: psql-persistent-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: psql-persistent-storage
          persistentVolumeClaim:
            claimName: psql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: schools
    tier: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432