index:
    path: /
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: index.html.twig
    methods: GET

list:
    path: /list
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: index.html.twig
    methods: GET

upoad:
    path: /upload
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: index.html.twig
    methods: GET
