---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-frontend
  labels:
    app: schools
    tier: application-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: schools
      tier: application-frontend
  template:
    metadata:
      labels:
        app: schools
        tier: application-frontend
    spec:
      containers:
        - name: nginx
          # CHANGEME to your image name and tag
          image: mariusbuescher/k8s-example-nginx-react:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-backend
  labels:
    app: schools
    tier: application-backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: schools
      tier: application-backend
  template:
    metadata:
      labels:
        app: schools
        tier: application-backend
    spec:
      containers:
        - name: php
          # CHANGEME to your image name and tag
          image: mariusbuescher/k8s-example-php-react:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: psql-pass
                  key: dsn
            - name: APP_ENV
              value: prod
            - name: TRUSTED_PROXIES
              value: 10.108.0.0/16
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthcheck/ping
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
      initContainers:
        - name: db-migration
          # CHANGEME to your image name and tag
          image: mariusbuescher/k8s-example-php-react:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: psql-pass
                  key: dsn
            - name: APP_ENV
              value: prod
          command: ['sh', '-c', 'bin/console doctrine:migrations:migrate --allow-no-migration -n']
---
apiVersion: v1
kind: Service
metadata:
  name: application-frontend
spec:
  selector:
    app: schools
    tier: application-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: application-backend
spec:
  selector:
    app: schools
    tier: application-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: application-ingress
spec:
  rules:
    - host: schools.localkube
      http:
        paths:
          - path: /build
            backend:
              serviceName: application-frontend
              servicePort: 80
          - path: /
            backend:
              serviceName: application-backend
              servicePort: 8080
